/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.aixtor.meepay.audit.management.service.base;

import com.aixtor.meepay.audit.management.model.AuditLogs;
import com.aixtor.meepay.audit.management.service.AuditLogsLocalService;
import com.aixtor.meepay.audit.management.service.AuditLogsLocalServiceUtil;
import com.aixtor.meepay.audit.management.service.persistence.AuditLogsPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the audit logs local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.aixtor.meepay.audit.management.service.impl.AuditLogsLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.aixtor.meepay.audit.management.service.impl.AuditLogsLocalServiceImpl
 * @generated
 */
public abstract class AuditLogsLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, AuditLogsLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AuditLogsLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AuditLogsLocalServiceUtil</code>.
	 */

	/**
	 * Adds the audit logs to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AuditLogsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param auditLogs the audit logs
	 * @return the audit logs that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AuditLogs addAuditLogs(AuditLogs auditLogs) {
		auditLogs.setNew(true);

		return auditLogsPersistence.update(auditLogs);
	}

	/**
	 * Creates a new audit logs with the primary key. Does not add the audit logs to the database.
	 *
	 * @param auditLogsId the primary key for the new audit logs
	 * @return the new audit logs
	 */
	@Override
	@Transactional(enabled = false)
	public AuditLogs createAuditLogs(long auditLogsId) {
		return auditLogsPersistence.create(auditLogsId);
	}

	/**
	 * Deletes the audit logs with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AuditLogsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param auditLogsId the primary key of the audit logs
	 * @return the audit logs that was removed
	 * @throws PortalException if a audit logs with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AuditLogs deleteAuditLogs(long auditLogsId) throws PortalException {
		return auditLogsPersistence.remove(auditLogsId);
	}

	/**
	 * Deletes the audit logs from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AuditLogsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param auditLogs the audit logs
	 * @return the audit logs that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AuditLogs deleteAuditLogs(AuditLogs auditLogs) {
		return auditLogsPersistence.remove(auditLogs);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return auditLogsPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AuditLogs.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return auditLogsPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.aixtor.meepay.audit.management.model.impl.AuditLogsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return auditLogsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.aixtor.meepay.audit.management.model.impl.AuditLogsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return auditLogsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return auditLogsPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return auditLogsPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AuditLogs fetchAuditLogs(long auditLogsId) {
		return auditLogsPersistence.fetchByPrimaryKey(auditLogsId);
	}

	/**
	 * Returns the audit logs matching the UUID and group.
	 *
	 * @param uuid the audit logs's UUID
	 * @param groupId the primary key of the group
	 * @return the matching audit logs, or <code>null</code> if a matching audit logs could not be found
	 */
	@Override
	public AuditLogs fetchAuditLogsByUuidAndGroupId(String uuid, long groupId) {
		return auditLogsPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the audit logs with the primary key.
	 *
	 * @param auditLogsId the primary key of the audit logs
	 * @return the audit logs
	 * @throws PortalException if a audit logs with the primary key could not be found
	 */
	@Override
	public AuditLogs getAuditLogs(long auditLogsId) throws PortalException {
		return auditLogsPersistence.findByPrimaryKey(auditLogsId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(auditLogsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AuditLogs.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("auditLogsId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			auditLogsLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AuditLogs.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"auditLogsId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(auditLogsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AuditLogs.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("auditLogsId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<AuditLogs>() {

				@Override
				public void performAction(AuditLogs auditLogs)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, auditLogs);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(AuditLogs.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return auditLogsPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement AuditLogsLocalServiceImpl#deleteAuditLogs(AuditLogs) to avoid orphaned data");
		}

		return auditLogsLocalService.deleteAuditLogs((AuditLogs)persistedModel);
	}

	@Override
	public BasePersistence<AuditLogs> getBasePersistence() {
		return auditLogsPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return auditLogsPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the audit logses matching the UUID and company.
	 *
	 * @param uuid the UUID of the audit logses
	 * @param companyId the primary key of the company
	 * @return the matching audit logses, or an empty list if no matches were found
	 */
	@Override
	public List<AuditLogs> getAuditLogsesByUuidAndCompanyId(
		String uuid, long companyId) {

		return auditLogsPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of audit logses matching the UUID and company.
	 *
	 * @param uuid the UUID of the audit logses
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of audit logses
	 * @param end the upper bound of the range of audit logses (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching audit logses, or an empty list if no matches were found
	 */
	@Override
	public List<AuditLogs> getAuditLogsesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<AuditLogs> orderByComparator) {

		return auditLogsPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the audit logs matching the UUID and group.
	 *
	 * @param uuid the audit logs's UUID
	 * @param groupId the primary key of the group
	 * @return the matching audit logs
	 * @throws PortalException if a matching audit logs could not be found
	 */
	@Override
	public AuditLogs getAuditLogsByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return auditLogsPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the audit logses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.aixtor.meepay.audit.management.model.impl.AuditLogsModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of audit logses
	 * @param end the upper bound of the range of audit logses (not inclusive)
	 * @return the range of audit logses
	 */
	@Override
	public List<AuditLogs> getAuditLogses(int start, int end) {
		return auditLogsPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of audit logses.
	 *
	 * @return the number of audit logses
	 */
	@Override
	public int getAuditLogsesCount() {
		return auditLogsPersistence.countAll();
	}

	/**
	 * Updates the audit logs in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AuditLogsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param auditLogs the audit logs
	 * @return the audit logs that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AuditLogs updateAuditLogs(AuditLogs auditLogs) {
		return auditLogsPersistence.update(auditLogs);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AuditLogsLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		auditLogsLocalService = (AuditLogsLocalService)aopProxy;

		_setLocalServiceUtilService(auditLogsLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AuditLogsLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AuditLogs.class;
	}

	protected String getModelClassName() {
		return AuditLogs.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = auditLogsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		AuditLogsLocalService auditLogsLocalService) {

		try {
			Field field = AuditLogsLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, auditLogsLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected AuditLogsLocalService auditLogsLocalService;

	@Reference
	protected AuditLogsPersistence auditLogsPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		AuditLogsLocalServiceBaseImpl.class);

}