components:
  schemas:
    Employee:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        employeeId:
          type: integer
          format: int64
        mobile:
          type: string
        email:
          type: string
        designationName:
          type: string
        departmentName:
          type: string
        branchName:
          type: string

    Branch:
      type: object
      properties:
        branchId:
          type: integer
          format: int64
        branchName:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string

    Department:
      type: object
      properties:
        departmentId:
          type: integer
          format: int64
        departmentName:
          type: string
        departmentHead:
          type: string

    Status:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    EmployeeByBranchRequest:
      type: object
      properties:
        branchId:
          description: The Branch Ids.
          type: integer
          format: int64
        branchName:
          description: The Branch Name.
          type: string
    EmployeeByBranchResponse:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/Status"
        employees:
          type: array
          items:
            $ref: "#/components/schemas/Employee"
        branches:
          type: array
          items:
            $ref: "#/components/schemas/Branch"
        totalEmployee:
          type: integer
          format: int64
    EmployeeByDepartmentRequest:
      type: object
      properties:
        departmentId:
          description: The Department IDs.
          type: integer
          format: int64
        departmentName:
          description: The Department Name.
          type: string
    EmployeeByDepartmentResponse:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/Status"
        employees:
          type: array
          items:
            $ref: "#/components/schemas/Employee"
        departments:
          type: array
          items:
            $ref: "#/components/schemas/Department"
        totalEmployee:
          type: integer
          format: int64

info:
  description: "AixtorEmployeeHeadless REST API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  title: "AixtorEmployeeHeadless"
  version: v1.0
openapi: 3.0.1

paths:
  /getEmployeesByBranch:
    post:
      description: Retrieve employees by branch details.
      tags: ["GetEmployeesByBranch"]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmployeeByBranchRequest"
          application/xml:
            schema:
              $ref: "#/components/schemas/EmployeeByBranchRequest"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmployeeByBranchResponse"
            application/xml:
              schema:
                $ref: "#/components/schemas/EmployeeByBranchResponse"

  /getEmployeesByDepartment:
    post:
      description: Retrieve employees by department details.
      tags: ["GetEmployeesByDepartment"]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmployeeByDepartmentRequest"
          application/xml:
            schema:
              $ref: "#/components/schemas/EmployeeByDepartmentRequest"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmployeeByDepartmentResponse"
            application/xml:
              schema:
                $ref: "#/components/schemas/EmployeeByDepartmentResponse"
