package com.aixtor.meepay.crud.constants;

public class MeepayEmployeeConstants {
    public static final String ROOT_URL = "http://localhost:8080/web/meepay/employee-crud";
	public static final String EMPLOYYEE_PREFILL = "employeePrefill";
	public static final String VIEW_JSP = "/html/employeeView.jsp"; 
	public static final String FORM_JSP = "/html/employeeForm.jsp"; 
	public static final String EMPLOYEE_ID = "employeeId";
	public static final String REQUEST_FROM = "requestFrom";
    public static final String COUNTRY_DROPDOWN = "countryDropdown";
    public static final String STATE_LIST = "stateList";
    public static final String STATE_DROPDOWN = "stateDropdown";
    public static final String CITY_LIST = "cityList";
    public static final String CREATE_DATE = "createDate";
    public static final String DATE_ZEROES = " 00:00:00.000000";
    public static final String DATE_FORMAT = "yyyy-MM-dd HH:mm:ss.SSSSSS";
    public static final String STATUS = "status";
    public static final String DELETE_ID = "deleteId";
    public static final String STORED_KEYWORD = "storedKeyWord";
    public static final String SUCCESS = "success";
    public static final String STORED_END_DATE = "storedEndDate";
    public static final String STORED_START_DATE = "storedStartDate";
    public static final String ERROR = "error";
    public static final String ERROR_MESSAGE = "Error occurred while fetching";
    public static final String NAME = "name";
    public static final String USER_LIST = "userList";
    public static final String DEPARTMENT_LIST = "departmentList";
    public static final String DEPARTMENT_NAME = "departmentName";
    public static final String BRANCH_NAME = "branchName";
    public static final String BRANCH_LIST = "branchList";
    public static final String FIRST_NAME = "firstName";
    public static final String LAST_NAME = "lastName";
    public static final String ADDRESS = "address";
	public static final String EMPLOYEE_LIST = "employeeList";
	public static final String DESIGNATION_LIST = "designationList";
	public static final String ROLES ="roles";
	public static final String USERNAME = "username";
	public static final String EMPTY = "";
	public static final String DOB = "dob";
	public static final String DEPARTMENT_PORTLET = "Department";
	public static final String DEPARTMENT = "department";
	public static final String BRANCH = "branch";
	public static final String BRANCH_PORTLET = "Branch";
	public static final String STATE = "state";
	public static final String COUNTRY = "country";
	public static final String KEYWORD = "keyword";
	public static final String END_DATE = "endDate";
	public static final String START_DATE = "startDate";
	public static final String PR = "%";
	public static final String MOBILE = "mobile";
	public static final String EMAIL = "email";
	public static final String COUNTRIES = "countries";
	public static final String DESIGNATION = "designation";

}
